In [7]:
import numpy as np

n=int(input("Enter n"))
mat=np.zeros((n,n+1))
roots=np.zeros(n+1)

def forwardElimination(mat):
    for j in range(n):
        row = input("Enter the first row of coefficients")
        row_arr=row.split(" ")
        for l in range(n):
            mat[j,l]=row_arr[l]
        mat[j,n]=row_arr[n]

    j=0
    while j<n :
        for k in range(j+1,n) :
            mat[k]=mat[k] - (mat[k,j]/mat[j,j])*mat[j]
        j+=1
forwardElimination(mat)

def backSubstitution(mat) : 
    global roots
    roots[n-1]=mat[n-1,n]/mat[n-1][n-1]
    p=n-2
    while p>-1:
        roots[p] = (mat[p,n] - sum((np.multiply(mat[p],roots))))/(mat[p,p])
        p-=1

backSubstitution(mat)
print("RRF :",mat)
print("Zeros are :",roots[0:n])

RRF : [[  40.        -1.         0.      -263.8964 ]
 [   0.         1.25      -1.       -25.46114]
 [   0.         0.         2.       706.18364]]
Zeros are : [-4.47964000e-02  2.62104544e+02  3.53091820e+02]


In [1]:
import numpy as np

n=int(input("Enter n"))
mat=np.zeros((n,n+1))
roots=np.zeros(n+1)

def forwardElimination(mat):
    for j in range(n):
        row = input("Enter the first row of coefficients")
        row_arr=row.split(" ")
        for l in range(n):
            mat[j,l]=row_arr[l]
        mat[j,n]=row_arr[n]

    j=0
    while j<n :
        for k in range(j+1,n) :
            mat[k]=mat[k] - (mat[k,j]/mat[j,j])*mat[j]
        j+=1
forwardElimination(mat)

def backSubstitution(mat) : 
    global roots
    roots[n-1]=mat[n-1,n]/mat[n-1][n-1]
    p=n-2
    while p>-1:
        roots[p] = (mat[p,n] - sum((np.multiply(mat[p],roots))))/(mat[p,p])
        p-=1

backSubstitution(mat)
print("RRF :",mat)
print("Zeros are :",roots[0:n])

RRF : [[ 130.          -30.            0.          500.        ]
 [   0.          -69.23076923    0.         -346.15384615]
 [   0.            0.         -120.         -700.        ]]
Zeros are : [5.         5.         5.83333333]


In [9]:
import numpy as np

n=int(input("Enter n"))
mat=np.zeros((n,n+1))
roots=np.zeros(n+1)

def forwardElimination(mat):
    for j in range(n):
        row = input("Enter the first row of coefficients")
        row_arr=row.split(" ")
        for l in range(n):
            mat[j,l]=row_arr[l]
        mat[j,n]=row_arr[n]

    j=0
    while j<n :
        for k in range(j+1,n) :
            mat[k]=mat[k] - (mat[k,j]/mat[j,j])*mat[j]
        j+=1
forwardElimination(mat)

def backSubstitution(mat) : 
    global roots
    roots[n-1]=mat[n-1,n]/mat[n-1][n-1]
    p=n-2
    while p>-1:
        roots[p] = (mat[p,n] - sum((np.multiply(mat[p],roots))))/(mat[p,p])
        p-=1

backSubstitution(mat)
print("RRF :",mat)
print("Zeros are :",roots[0:n])

RRF : [[  6.          -4.          -2.          20.        ]
 [  0.         -15.33333333   9.33333333 -13.33333333]
 [  0.           0.          -8.65217391 -14.7826087 ]]
Zeros are : [5.1758794  1.90954774 1.70854271]
